# Generated by Django 4.2.3 on 2023-07-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1name', models.CharField(max_length=100, null=True)),
                ('company1designation', models.CharField(max_length=100, null=True)),
                ('company1salary', models.CharField(max_length=100, null=True)),
                ('company1duration', models.CharField(max_length=100, null=True)),
                ('compamy2name', models.CharField(max_length=100, null=True)),
                ('company2designation', models.CharField(max_length=100, null=True)),
                ('company2salary', models.CharField(max_length=100, null=True)),
                ('company2duration', models.CharField(max_length=100, null=True)),
                ('company3name', models.CharField(max_length=100, null=True)),
                ('company3designation', models.CharField(max_length=100, null=True)),
                ('company3salary', models.CharField(max_length=100, null=True)),
                ('company3duration', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pg', models.CharField(max_length=100, null=True)),
                ('schoolcollege_pg', models.CharField(max_length=100, null=True)),
                ('year_of_passing_pg', models.CharField(max_length=20, null=True)),
                ('percentage_pg', models.CharField(max_length=30, null=True)),
                ('course_grad', models.CharField(max_length=100, null=True)),
                ('schoolcollege_grad', models.CharField(max_length=100, null=True)),
                ('year_of_passing_grad', models.CharField(max_length=20, null=True)),
                ('percentage_grad', models.CharField(max_length=30, null=True)),
                ('course_hsec', models.CharField(max_length=100, null=True)),
                ('schoolcollege_hsec', models.CharField(max_length=100, null=True)),
                ('year_of_passin_hsec', models.CharField(max_length=20, null=True)),
                ('percentage_hsec', models.CharField(max_length=30, null=True)),
                ('course_sec', models.CharField(max_length=100, null=True)),
                ('schoolcollege_sec', models.CharField(max_length=100, null=True)),
                ('year_of_passin_sec', models.CharField(max_length=20, null=True)),
                ('percentage_sec', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
