# Generated by Django 4.2.3 on 2023-07-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='compamy2name',
            new_name='company2name',
        ),
    ]
